INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(999,'Unknown');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(532,'thrillers/suspense');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(531,'supernatural  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(530,'sports  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(529,'romance  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(528,'melodramas or women''s weepers');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(527,'guy  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(526,'film noir ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(525,'fantasy  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(524,'disaster  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(523,'detective/mystery  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(522,'chick flicks (or gal ) ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(521,'biographical  (biopics)');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(520,'silent  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(519,'sexual/erotic  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(518,'serial  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(517,'documentary  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(516,'cult  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(514,'classic  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(513,'childrens/kids/family  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(512,'British  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(511,'animated  ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(510,'westerns ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(509,'war ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(508,'science fiction ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(507,'musicals ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(506,'horror ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(505,'epics/historical ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(504,'drama ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(503,'crime/gangster ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(502,'comedy ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(501,'adventure ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(500,'action ');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(161,'Hip Hop');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(160,'Pop');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(159,'Rap');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(158,'Fusion');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(157,'R&B');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(156,'Gospel');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(155,'Funk Rock');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(154,'New Orleans Jazz');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(153,'Post Bop');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(152,'Holiday Music');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(151,'Smooth Jazz');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(150,'Jam Rock');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(149,'Jazz Fusion');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(148,'Soul');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(147,'SynthPop');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(146,'JPop');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(145,'Anime');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(144,'Thrash Metal');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(143,'Salsa');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(142,'Merengue');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(141,'Christian Rock');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(140,'Contemporary R&B');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(139,'Crossover');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(138,'Black Metal');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(137,'Heavy Metal');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(136,'Christian Gangsta');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(135,'Beat');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(134,'Polsk Punk');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(133,'Negerpunk');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(132,'BritPop');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(131,'Indie');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(130,'Terror');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(129,'Hardcore');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(128,'Club House');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(127,'Drum & Bass');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(126,'Goa');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(125,'Dance Hall');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(124,'Euro House');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(123,'Acapella');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(122,'Drum Solo');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(121,'Punk Rock');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(120,'Duet');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(119,'Freestyle');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(118,'Rhytmic Soul');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(117,'Power Ballad');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(116,'Ballad');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(115,'Folklore');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(114,'Samba');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(113,'Tango');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(112,'Club');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(111,'Slow Jam');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(110,'Satire');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(109,'Porn Groove');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(108,'Primus');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(107,'Booty Bass');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(106,'Symphony');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(105,'Sonata');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(104,'Chamber Music');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(103,'Opera');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(102,'Chanson');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(101,'Speech');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(100,'Humour');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(99,'Acoustic');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(98,'Easy Listening');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(97,'Chorus');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(96,'Big Band');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(95,'Slow Rock');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(94,'Symphonic Rock');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(93,'Psychedelic Rock');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(92,'Progressive Rock');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(91,'Gothic Rock');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(90,'Avantgarde');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(89,'Bluegrass');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(88,'Celtic');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(87,'Revival');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(86,'Latin');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(85,'Bebob');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(84,'Fast Fusion');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(83,'Swing');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(82,'National Folk');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(81,'Folk Rock');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(80,'Folk');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(79,'Hard Rock');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(78,'Rock & Roll');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(77,'Musical');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(76,'Retro');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(75,'Polka');
INSERT INTO "DBA"."AV_GENRE" ("genre_id","description") VALUES(74,'Acid Jazz');