INSERT INTO "DBA"."AV_MEDIA_TYPE" ("media_type_id","description") VALUES(1,'Compact Disc');
INSERT INTO "DBA"."AV_MEDIA_TYPE" ("media_type_id","description") VALUES(2,'Digital Video Disc (DVD)');
INSERT INTO "DBA"."AV_MEDIA_TYPE" ("media_type_id","description") VALUES(3,'Cassette Tape');
INSERT INTO "DBA"."AV_MEDIA_TYPE" ("media_type_id","description") VALUES(4,'Album (LP)');
INSERT INTO "DBA"."AV_MEDIA_TYPE" ("media_type_id","description") VALUES(5,'Digital Audio Tape');
INSERT INTO "DBA"."AV_MEDIA_TYPE" ("media_type_id","description") VALUES(6,'Reel to Reel');
INSERT INTO "DBA"."AV_MEDIA_TYPE" ("media_type_id","description") VALUES(7,'Video Cassette (VHS)');
INSERT INTO "DBA"."AV_MEDIA_TYPE" ("media_type_id","description") VALUES(8,'Video Cassette (Beta)');
INSERT INTO "DBA"."AV_MEDIA_TYPE" ("media_type_id","description") VALUES(9,'Laser Disc');
INSERT INTO "DBA"."AV_MEDIA_TYPE" ("media_type_id","description") VALUES(10,'Blue Ray');
INSERT INTO "DBA"."AV_MEDIA_TYPE" ("media_type_id","description") VALUES(11,'Other');