//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.23 at 11:17:17 PM CDT 
//


package com.xml.schema.bindings;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml.schema.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReplyStatusTypeReturnCode_QNAME = new QName("", "return_code");
    private final static QName _ReplyStatusTypeMessage_QNAME = new QName("", "message");
    private final static QName _ReplyStatusTypeExtMessage_QNAME = new QName("", "ext_message");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml.schema.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenericXactCriteriaType }
     * 
     */
    public GenericXactCriteriaType createGenericXactCriteriaType() {
        return new GenericXactCriteriaType();
    }

    /**
     * Create an instance of {@link RQAuthenticationUserAppRoles }
     * 
     */
    public RQAuthenticationUserAppRoles createRQAuthenticationUserAppRoles() {
        return new RQAuthenticationUserAppRoles();
    }

    /**
     * Create an instance of {@link ResourceSubtypeType }
     * 
     */
    public ResourceSubtypeType createResourceSubtypeType() {
        return new ResourceSubtypeType();
    }

    /**
     * Create an instance of {@link CodeGroupType }
     * 
     */
    public CodeGroupType createCodeGroupType() {
        return new CodeGroupType();
    }

    /**
     * Create an instance of {@link CommonContactCriteria }
     * 
     */
    public CommonContactCriteria createCommonContactCriteria() {
        return new CommonContactCriteria();
    }

    /**
     * Create an instance of {@link MimeContentType }
     * 
     */
    public MimeContentType createMimeContentType() {
        return new MimeContentType();
    }

    /**
     * Create an instance of {@link RQBusinessContactUpdate }
     * 
     */
    public RQBusinessContactUpdate createRQBusinessContactUpdate() {
        return new RQBusinessContactUpdate();
    }

    /**
     * Create an instance of {@link RQCommonContactSearch }
     * 
     */
    public RQCommonContactSearch createRQCommonContactSearch() {
        return new RQCommonContactSearch();
    }

    /**
     * Create an instance of {@link SalesOrderType }
     * 
     */
    public SalesOrderType createSalesOrderType() {
        return new SalesOrderType();
    }

    /**
     * Create an instance of {@link SalesOrderItemType }
     * 
     */
    public SalesOrderItemType createSalesOrderItemType() {
        return new SalesOrderItemType();
    }

    /**
     * Create an instance of {@link RSAccountingInvoiceSalesOrder }
     * 
     */
    public RSAccountingInvoiceSalesOrder createRSAccountingInvoiceSalesOrder() {
        return new RSAccountingInvoiceSalesOrder();
    }

    /**
     * Create an instance of {@link RSProjecttrackerClinetProjects }
     * 
     */
    public RSProjecttrackerClinetProjects createRSProjecttrackerClinetProjects() {
        return new RSProjecttrackerClinetProjects();
    }

    /**
     * Create an instance of {@link SalesOrderInvoiceResultType }
     * 
     */
    public SalesOrderInvoiceResultType createSalesOrderInvoiceResultType() {
        return new SalesOrderInvoiceResultType();
    }

    /**
     * Create an instance of {@link MimeType }
     * 
     */
    public MimeType createMimeType() {
        return new MimeType();
    }

    /**
     * Create an instance of {@link RSGenreicTransactionSearch.TransactionTypes }
     * 
     */
    public RSGenreicTransactionSearch.TransactionTypes createRSGenreicTransactionSearchTransactionTypes() {
        return new RSGenreicTransactionSearch.TransactionTypes();
    }

    /**
     * Create an instance of {@link ZipcodeFullType }
     * 
     */
    public ZipcodeFullType createZipcodeFullType() {
        return new ZipcodeFullType();
    }

    /**
     * Create an instance of {@link RQProjecttrackerClinetProjects }
     * 
     */
    public RQProjecttrackerClinetProjects createRQProjecttrackerClinetProjects() {
        return new RQProjecttrackerClinetProjects();
    }

    /**
     * Create an instance of {@link RSGenreicTransactionSearch.Transactions }
     * 
     */
    public RSGenreicTransactionSearch.Transactions createRSGenreicTransactionSearchTransactions() {
        return new RSGenreicTransactionSearch.Transactions();
    }

    /**
     * Create an instance of {@link ResourceExtType }
     * 
     */
    public ResourceExtType createResourceExtType() {
        return new ResourceExtType();
    }

    /**
     * Create an instance of {@link RQAuthenticationLogin }
     * 
     */
    public RQAuthenticationLogin createRQAuthenticationLogin() {
        return new RQAuthenticationLogin();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link CustomerCriteriaType }
     * 
     */
    public CustomerCriteriaType createCustomerCriteriaType() {
        return new CustomerCriteriaType();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public CustomerType createCustomerType() {
        return new CustomerType();
    }

    /**
     * Create an instance of {@link RQPostalSearch.PostalCriteria }
     * 
     */
    public RQPostalSearch.PostalCriteria createRQPostalSearchPostalCriteria() {
        return new RQPostalSearch.PostalCriteria();
    }

    /**
     * Create an instance of {@link ApplicationType }
     * 
     */
    public ApplicationType createApplicationType() {
        return new ApplicationType();
    }

    /**
     * Create an instance of {@link RSPersonalContactSearch }
     * 
     */
    public RSPersonalContactSearch createRSPersonalContactSearch() {
        return new RSPersonalContactSearch();
    }

    /**
     * Create an instance of {@link ZipcodeCriteriaType }
     * 
     */
    public ZipcodeCriteriaType createZipcodeCriteriaType() {
        return new ZipcodeCriteriaType();
    }

    /**
     * Create an instance of {@link ResourcetypeType }
     * 
     */
    public ResourcetypeType createResourcetypeType() {
        return new ResourcetypeType();
    }

    /**
     * Create an instance of {@link RSAuthenticationUserResourceAccess }
     * 
     */
    public RSAuthenticationUserResourceAccess createRSAuthenticationUserResourceAccess() {
        return new RSAuthenticationUserResourceAccess();
    }

    /**
     * Create an instance of {@link AppRoleType }
     * 
     */
    public AppRoleType createAppRoleType() {
        return new AppRoleType();
    }

    /**
     * Create an instance of {@link TimezoneType }
     * 
     */
    public TimezoneType createTimezoneType() {
        return new TimezoneType();
    }

    /**
     * Create an instance of {@link RQCustomerSearch }
     * 
     */
    public RQCustomerSearch createRQCustomerSearch() {
        return new RQCustomerSearch();
    }

    /**
     * Create an instance of {@link RQAuthenticationResource }
     * 
     */
    public RQAuthenticationResource createRQAuthenticationResource() {
        return new RQAuthenticationResource();
    }

    /**
     * Create an instance of {@link RQCodeDetailSearch }
     * 
     */
    public RQCodeDetailSearch createRQCodeDetailSearch() {
        return new RQCodeDetailSearch();
    }

    /**
     * Create an instance of {@link RSAuthenticationUserAppcheck }
     * 
     */
    public RSAuthenticationUserAppcheck createRSAuthenticationUserAppcheck() {
        return new RSAuthenticationUserAppcheck();
    }

    /**
     * Create an instance of {@link XactType }
     * 
     */
    public XactType createXactType() {
        return new XactType();
    }

    /**
     * Create an instance of {@link RQAuthenticationLogout }
     * 
     */
    public RQAuthenticationLogout createRQAuthenticationLogout() {
        return new RQAuthenticationLogout();
    }

    /**
     * Create an instance of {@link LookupCodeType }
     * 
     */
    public LookupCodeType createLookupCodeType() {
        return new LookupCodeType();
    }

    /**
     * Create an instance of {@link RSGenreicTransactionSearch }
     * 
     */
    public RSGenreicTransactionSearch createRSGenreicTransactionSearch() {
        return new RSGenreicTransactionSearch();
    }

    /**
     * Create an instance of {@link RQAuthenticationUserResourceAccess }
     * 
     */
    public RQAuthenticationUserResourceAccess createRQAuthenticationUserResourceAccess() {
        return new RQAuthenticationUserResourceAccess();
    }

    /**
     * Create an instance of {@link RQCodeLookup }
     * 
     */
    public RQCodeLookup createRQCodeLookup() {
        return new RQCodeLookup();
    }

    /**
     * Create an instance of {@link ResourceAccessType }
     * 
     */
    public ResourceAccessType createResourceAccessType() {
        return new ResourceAccessType();
    }

    /**
     * Create an instance of {@link CountryCriteriaType }
     * 
     */
    public CountryCriteriaType createCountryCriteriaType() {
        return new CountryCriteriaType();
    }

    /**
     * Create an instance of {@link RSAuthenticationLogout }
     * 
     */
    public RSAuthenticationLogout createRSAuthenticationLogout() {
        return new RSAuthenticationLogout();
    }

    /**
     * Create an instance of {@link UserAppRolesType }
     * 
     */
    public UserAppRolesType createUserAppRolesType() {
        return new UserAppRolesType();
    }

    /**
     * Create an instance of {@link CommonContactType }
     * 
     */
    public CommonContactType createCommonContactType() {
        return new CommonContactType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link UserLoginType }
     * 
     */
    public UserLoginType createUserLoginType() {
        return new UserLoginType();
    }

    /**
     * Create an instance of {@link RQBusinessContactDelete }
     * 
     */
    public RQBusinessContactDelete createRQBusinessContactDelete() {
        return new RQBusinessContactDelete();
    }

    /**
     * Create an instance of {@link RQPersonalContactSearch }
     * 
     */
    public RQPersonalContactSearch createRQPersonalContactSearch() {
        return new RQPersonalContactSearch();
    }

    /**
     * Create an instance of {@link StatesCriteriaType }
     * 
     */
    public StatesCriteriaType createStatesCriteriaType() {
        return new StatesCriteriaType();
    }

    /**
     * Create an instance of {@link RQUsStatesSearch }
     * 
     */
    public RQUsStatesSearch createRQUsStatesSearch() {
        return new RQUsStatesSearch();
    }

    /**
     * Create an instance of {@link RSAuthenticationLogin }
     * 
     */
    public RSAuthenticationLogin createRSAuthenticationLogin() {
        return new RSAuthenticationLogin();
    }

    /**
     * Create an instance of {@link RQAuthenticationUserAppcheck }
     * 
     */
    public RQAuthenticationUserAppcheck createRQAuthenticationUserAppcheck() {
        return new RQAuthenticationUserAppcheck();
    }

    /**
     * Create an instance of {@link CodeDetailType }
     * 
     */
    public CodeDetailType createCodeDetailType() {
        return new CodeDetailType();
    }

    /**
     * Create an instance of {@link XactItemType }
     * 
     */
    public XactItemType createXactItemType() {
        return new XactItemType();
    }

    /**
     * Create an instance of {@link FullGroupType }
     * 
     */
    public FullGroupType createFullGroupType() {
        return new FullGroupType();
    }

    /**
     * Create an instance of {@link RQAuthenticationResourceSubtype }
     * 
     */
    public RQAuthenticationResourceSubtype createRQAuthenticationResourceSubtype() {
        return new RQAuthenticationResourceSubtype();
    }

    /**
     * Create an instance of {@link RSCodeLookup }
     * 
     */
    public RSCodeLookup createRSCodeLookup() {
        return new RSCodeLookup();
    }

    /**
     * Create an instance of {@link RSCodeDetailSearch }
     * 
     */
    public RSCodeDetailSearch createRSCodeDetailSearch() {
        return new RSCodeDetailSearch();
    }

    /**
     * Create an instance of {@link RSBusinessContactUpdate }
     * 
     */
    public RSBusinessContactUpdate createRSBusinessContactUpdate() {
        return new RSBusinessContactUpdate();
    }

    /**
     * Create an instance of {@link ReplyStatusType }
     * 
     */
    public ReplyStatusType createReplyStatusType() {
        return new ReplyStatusType();
    }

    /**
     * Create an instance of {@link IpCriteriaType }
     * 
     */
    public IpCriteriaType createIpCriteriaType() {
        return new IpCriteriaType();
    }

    /**
     * Create an instance of {@link RSBusinessContactSearch }
     * 
     */
    public RSBusinessContactSearch createRSBusinessContactSearch() {
        return new RSBusinessContactSearch();
    }

    /**
     * Create an instance of {@link RSCommonReply }
     * 
     */
    public RSCommonReply createRSCommonReply() {
        return new RSCommonReply();
    }

    /**
     * Create an instance of {@link BusinessContactCriteria }
     * 
     */
    public BusinessContactCriteria createBusinessContactCriteria() {
        return new BusinessContactCriteria();
    }

    /**
     * Create an instance of {@link RSCommonContactSearch }
     * 
     */
    public RSCommonContactSearch createRSCommonContactSearch() {
        return new RSCommonContactSearch();
    }

    /**
     * Create an instance of {@link RQContentSearch }
     * 
     */
    public RQContentSearch createRQContentSearch() {
        return new RQContentSearch();
    }

    /**
     * Create an instance of {@link RSUsStatesSearch }
     * 
     */
    public RSUsStatesSearch createRSUsStatesSearch() {
        return new RSUsStatesSearch();
    }

    /**
     * Create an instance of {@link PersonContactCriteria }
     * 
     */
    public PersonContactCriteria createPersonContactCriteria() {
        return new PersonContactCriteria();
    }

    /**
     * Create an instance of {@link StateType }
     * 
     */
    public StateType createStateType() {
        return new StateType();
    }

    /**
     * Create an instance of {@link BusinessType }
     * 
     */
    public BusinessType createBusinessType() {
        return new BusinessType();
    }

    /**
     * Create an instance of {@link ZipcodeType }
     * 
     */
    public ZipcodeType createZipcodeType() {
        return new ZipcodeType();
    }

    /**
     * Create an instance of {@link UserSessionType }
     * 
     */
    public UserSessionType createUserSessionType() {
        return new UserSessionType();
    }

    /**
     * Create an instance of {@link RQPostalSearch }
     * 
     */
    public RQPostalSearch createRQPostalSearch() {
        return new RQPostalSearch();
    }

    /**
     * Create an instance of {@link RSAuthenticationResourceSubtype }
     * 
     */
    public RSAuthenticationResourceSubtype createRSAuthenticationResourceSubtype() {
        return new RSAuthenticationResourceSubtype();
    }

    /**
     * Create an instance of {@link CitytypeType }
     * 
     */
    public CitytypeType createCitytypeType() {
        return new CitytypeType();
    }

    /**
     * Create an instance of {@link TimezoneCriteriaType }
     * 
     */
    public TimezoneCriteriaType createTimezoneCriteriaType() {
        return new TimezoneCriteriaType();
    }

    /**
     * Create an instance of {@link RQBusinessContactSearch }
     * 
     */
    public RQBusinessContactSearch createRQBusinessContactSearch() {
        return new RQBusinessContactSearch();
    }

    /**
     * Create an instance of {@link ResourceType }
     * 
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link CountryType }
     * 
     */
    public CountryType createCountryType() {
        return new CountryType();
    }

    /**
     * Create an instance of {@link RQAccountingInvoiceSalesOrder }
     * 
     */
    public RQAccountingInvoiceSalesOrder createRQAccountingInvoiceSalesOrder() {
        return new RQAccountingInvoiceSalesOrder();
    }

    /**
     * Create an instance of {@link LookupCodeCriteriaType }
     * 
     */
    public LookupCodeCriteriaType createLookupCodeCriteriaType() {
        return new LookupCodeCriteriaType();
    }

    /**
     * Create an instance of {@link RSGenreicTransactionSearch.TransactionSubTypes }
     * 
     */
    public RSGenreicTransactionSearch.TransactionSubTypes createRSGenreicTransactionSearchTransactionSubTypes() {
        return new RSGenreicTransactionSearch.TransactionSubTypes();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link ClientProjectType }
     * 
     */
    public ClientProjectType createClientProjectType() {
        return new ClientProjectType();
    }

    /**
     * Create an instance of {@link RSAuthenticationUserProfile }
     * 
     */
    public RSAuthenticationUserProfile createRSAuthenticationUserProfile() {
        return new RSAuthenticationUserProfile();
    }

    /**
     * Create an instance of {@link PaginationType }
     * 
     */
    public PaginationType createPaginationType() {
        return new PaginationType();
    }

    /**
     * Create an instance of {@link RQGenreicTransactionSearch }
     * 
     */
    public RQGenreicTransactionSearch createRQGenreicTransactionSearch() {
        return new RQGenreicTransactionSearch();
    }

    /**
     * Create an instance of {@link RSContentSearch }
     * 
     */
    public RSContentSearch createRSContentSearch() {
        return new RSContentSearch();
    }

    /**
     * Create an instance of {@link RSBusinessContactDelete }
     * 
     */
    public RSBusinessContactDelete createRSBusinessContactDelete() {
        return new RSBusinessContactDelete();
    }

    /**
     * Create an instance of {@link RoleType }
     * 
     */
    public RoleType createRoleType() {
        return new RoleType();
    }

    /**
     * Create an instance of {@link RSAuthenticationUserAppRoles }
     * 
     */
    public RSAuthenticationUserAppRoles createRSAuthenticationUserAppRoles() {
        return new RSAuthenticationUserAppRoles();
    }

    /**
     * Create an instance of {@link UserAppLoginCheckType }
     * 
     */
    public UserAppLoginCheckType createUserAppLoginCheckType() {
        return new UserAppLoginCheckType();
    }

    /**
     * Create an instance of {@link RSAuthenticationResource }
     * 
     */
    public RSAuthenticationResource createRSAuthenticationResource() {
        return new RSAuthenticationResource();
    }

    /**
     * Create an instance of {@link XacttypeType }
     * 
     */
    public XacttypeType createXacttypeType() {
        return new XacttypeType();
    }

    /**
     * Create an instance of {@link RSCustomerSearch }
     * 
     */
    public RSCustomerSearch createRSCustomerSearch() {
        return new RSCustomerSearch();
    }

    /**
     * Create an instance of {@link XactItemtypeType }
     * 
     */
    public XactItemtypeType createXactItemtypeType() {
        return new XactItemtypeType();
    }

    /**
     * Create an instance of {@link UserLogoutType }
     * 
     */
    public UserLogoutType createUserLogoutType() {
        return new UserLogoutType();
    }

    /**
     * Create an instance of {@link RQAuthenticationUserProfile }
     * 
     */
    public RQAuthenticationUserProfile createRQAuthenticationUserProfile() {
        return new RQAuthenticationUserProfile();
    }

    /**
     * Create an instance of {@link RSPostalSearch }
     * 
     */
    public RSPostalSearch createRSPostalSearch() {
        return new RSPostalSearch();
    }

    /**
     * Create an instance of {@link IpDetails }
     * 
     */
    public IpDetails createIpDetails() {
        return new IpDetails();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link OrderByType }
     * 
     */
    public OrderByType createOrderByType() {
        return new OrderByType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "return_code", scope = ReplyStatusType.class)
    public JAXBElement<BigInteger> createReplyStatusTypeReturnCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_ReplyStatusTypeReturnCode_QNAME, BigInteger.class, ReplyStatusType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "message", scope = ReplyStatusType.class)
    public JAXBElement<String> createReplyStatusTypeMessage(String value) {
        return new JAXBElement<String>(_ReplyStatusTypeMessage_QNAME, String.class, ReplyStatusType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ext_message", scope = ReplyStatusType.class)
    public JAXBElement<String> createReplyStatusTypeExtMessage(String value) {
        return new JAXBElement<String>(_ReplyStatusTypeExtMessage_QNAME, String.class, ReplyStatusType.class, value);
    }

}
