CREATE TABLE address2 
  (id integer NOT NULL DEFAULT autoincrement, 
   addresstype_id integer NOT NULL DEFAULT NULL, 
   perbus_id integer DEFAULT NULL, 
   address1 char(25) DEFAULT NULL, 
   address2 char(25) DEFAULT NULL, 
   address3 char(25) DEFAULT NULL, 
   address4 char(25) DEFAULT NULL, 
   city_id integer DEFAULT NULL, 
   state_id integer DEFAULT NULL, 
   country_id integer DEFAULT NULL, 
   zip_code char(5) DEFAULT NULL, 
   zip_ext char(4) DEFAULT NULL, 
   phone_home char(13) DEFAULT NULL,
   phone_work char(13) DEFAULT NULL,
   phone_workext char(8) DEFAULT NULL,
   phone_business char(13) DEFAULT NULL,
   phone_celluar char(13) DEFAULT NULL,
   phone_fax char(13) DEFAULT NULL,
   phone_pager char(13) DEFAULT NULL,
   phone_other char(13) DEFAULT NULL,
   internet_address char(80) DEFAULT NULL, 
   email char(50) DEFAULT NULL, 
   date_created date DEFAULT current date, 
   date_updated date DEFAULT current date, 
   user_id char(8) DEFAULT 'DBA', 
   comment_id integer DEFAULT NULL , 
   PRIMARY KEY (address_id)) ;