
%/********************************************************************
%         CREATE INDEXES ON ALL MUSIC VIDEO TABLES THAT APPLY
%********************************************************************/
CREATE INDEX AVD_CATEGORY_NDX ON AUDIO_VIDEO_DETAIL (CATEGORY);
CREATE INDEX AVD_MEDIATYPE_NDX ON AUDIO_VIDEO_DETAIL (MEDIA_TYPE);
CREATE INDEX AVD_YEARRECORD_NDX ON AUDIO_VIDEO_DETAIL (YEAR_RECORDED);
CREATE INDEX AVD_CATEGORY_MEDIATYPE_NDX ON AUDIO_VIDEO_DETAIL (CATEGORY, MEDIA_TYPE);
CREATE INDEX AVD_1_NDX ON AUDIO_VIDEO_DETAIL (ASSET_MASTER_ID, CATEGORY, MEDIA_TYPE);
CREATE INDEX AVD_GENERAL_NDX ON AUDIO_VIDEO_DETAIL (CATEGORY, MEDIA_TYPE, YEAR_RECORDED);

CREATE INDEX AVD_ROW_NDX ON AUDIO_VIDEO_TRACKS
     (TRACK_NUMBER, AUDIO_VIDEO_DETAIL_ID, TRACK_TITLE, TRACK_HOURS, TRACK_MINUTES, TRACK_SECONDS);

CREATE INDEX AVT_TRACKNUMBER_NDX ON AUDIO_VIDEO_TRACKS (TRACK_NUMBER);
CREATE INDEX AVT_TITLE_NDX ON AUDIO_VIDEO_TRACKS (TRACK_TITLE);
CREATE INDEX AVT_HOURS_NDX ON AUDIO_VIDEO_TRACKS (TRACK_HOURS);
CREATE INDEX AVT_MINUETS_NDX ON AUDIO_VIDEO_TRACKS (TRACK_MINUTES);
CREATE INDEX AVT_SECONDS_NDX ON AUDIO_VIDEO_TRACKS (TRACK_SECONDS);
CREATE INDEX AVT_PROJSIDE_NDX ON AUDIO_VIDEO_TRACKS (PROJECT_SIDE);
CREATE INDEX AVT_TRACKPRODUCER_NDX ON AUDIO_VIDEO_TRACKS (TRACK_PRODUCER);
CREATE INDEX AVT_TRACKCOMPOSER_NDX ON AUDIO_VIDEO_TRACKS (TRACK_COMPOSER);
CREATE INDEX AVT_TRACKLYRICIST_NDX ON AUDIO_VIDEO_TRACKS (TRACK_LYRICIST);
CREATE INDEX AVT_TRACKDETAILS_NDX ON AUDIO_VIDEO_TRACKS
     (TRACK_NUMBER, TRACK_TITLE, TRACK_HOURS, TRACK_MINUTES, TRACK_SECONDS);


